
@baseUrl = http://localhost:8100/api
# @baseUrl = https://app-latest-4nnj.onrender.com/api
@accessToken = ""
@refreshToken = ""


### REGISTER USER ###
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "name": "test_user",
    "email": "testuser@example.com",
    "password": "password123"
}

### LOGIN REQUEST###
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "testuser@example.com",
    "password": "password123"
}

@accessToken = {{login.response.body.data.accessToken}}



### GET CURRENT USER ###
GET {{baseUrl}}/user
Content-Type:  application/json
Authorization: Bearer {{accessToken}}

