@baseUrl = http://localhost:8100

# Tokens from login
@loginAccess_token = ""
@loginRefresh_token = ""

# Tokens from refresh
@newAccess_token = ""
@newRefresh_token = ""

### REGISTER USER ###
POST {{baseUrl}}/api/auth/register
Content-Type: application/json
Authorization: Bearer {{adminAccess_token}}

{
    "name": "test_user",
    "email": "testuser@example.com",
    "password": "password123"
}

### LOGIN REQUEST ###
# @name login
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
    "email": "testuser@example.com",
    "password": "password123"
}

@loginAccess_token = {{login.response.body.data.access_token}}
@loginRefresh_token = {{login.response.body.data.refresh_token}}

### GET CURRENT USER (using login token) ###
GET {{baseUrl}}/api/user
Authorization: Bearer {{loginAccess_token}}

### REFRESH TOKEN ###
# @name refresh
POST {{baseUrl}}/api/auth/refresh
Content-Type: application/json

{
    "refresh_token": "{{loginRefresh_token}}"
}

@newAccess_token = {{refresh.response.body.data.access_token}}
@newRefresh_token = {{refresh.response.body.data.refresh_token}}
### GET CURRENT USER (using refreshed token) ###
GET {{baseUrl}}/api/user
Authorization: Bearer {{newAccess_token}}


### REGISTER ANOTHER USER ###
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
    "name": "Max Payne",
    "email": "max.payne@example.com",
    "password": "password@1234"
}

### LOGIN ADMIN USER ###
# @name admin
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
    "email": "admin@example.com",
    "password": "admin123"
}

@adminAccess_token = {{admin.response.body.data.access_token}}
@adminRefresh_token = {{admin.response.body.data.refresh_token}}

### GET ADMIN USER ###
GET {{baseUrl}}/api/user
Authorization: Bearer {{adminAccess_token}}


### CREATE PERMISSION ###
POST {{baseUrl}}/api/admin/permissions
Authorization: Bearer {{adminAccess_token}}
Content-Type: application/json

{
    "name": "ticket.assign",
    "description": "Assign tickets to users"
}


### LIST PERMISSIONS ###
GET {{baseUrl}}/api/admin/permissions
Authorization: Bearer {{adminAccess_token}}



### CREATE ROLE ###
POST {{baseUrl}}/api/admin/roles
Authorization: Bearer {{adminAccess_token}}
Content-Type: application/json

{
    "name": "SUPPORT",
    "description": "Support team role",
    "permissionIds": [1, 2]
}


### LIST ROLES ###
GET {{baseUrl}}/api/admin/roles
Authorization: Bearer {{adminAccess_token}}

### CRUD USER OPERATIONS ###

### CREATE USER ###
POST {{baseUrl}}/api/admin/users
Authorization: Bearer {{adminAccess_token}}
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@example.com",
    "password": "password123",
    "roleIds": [1]
}


### LIST USERS ###
GET {{baseUrl}}/api/admin/users
Authorization: Bearer {{adminAccess_token}}


### ASSIGN ROLES TO USER ###
POST {{baseUrl}}/api/admin/users/2/roles
Authorization: Bearer {{adminAccess_token}}
Content-Type: application/json

{
    "roleIds": [2]   // Add more roles
}
