@baseUrl = http://localhost:8100

# Tokens from login
@loginAccessToken = ""
@loginRefreshToken = ""

# Tokens from refresh
@newAccessToken = ""
@newRefreshToken = ""

### REGISTER USER ###
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
    "name": "test_user",
    "email": "testuser@example.com",
    "password": "password123"
}

### LOGIN REQUEST ###
# @name login
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
    "email": "testuser@example.com",
    "password": "password123"
}

@loginAccessToken = {{login.response.body.data.accessToken}}
@loginRefreshToken = {{login.response.body.data.refreshToken}}

### GET CURRENT USER (using login token) ###
GET {{baseUrl}}/api/user
Authorization: Bearer {{loginAccessToken}}

### REFRESH TOKEN ###
# @name refresh
POST {{baseUrl}}/api/auth/refresh
Content-Type: application/json

{
    "refreshToken": "{{loginRefreshToken}}"
}

@newAccessToken = {{refresh.response.body.data.accessToken}}
@newRefreshToken = {{refresh.response.body.data.refreshToken}}

### GET CURRENT USER (using refreshed token) ###
GET {{baseUrl}}/api/user
Authorization: Bearer {{newAccessToken}}
