@baseUrl = http://localhost:8100

### LOGIN ADMIN USER ###
# @name admin
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
    "email": "admin@example.com",
    "password": "admin123"
}

@adminAccess_token = {{admin.response.body.data.access_token}}
@adminRefresh_token = {{admin.response.body.data.refresh_token}}


### CRUD USER OPERATIONS ###

### CREATE USER ###
POST {{baseUrl}}/api/admin/users
Authorization: Bearer {{adminAccess_token}}
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@example.com",
    "password": "password1234",
    "roleIds": [2]
}

### LIST PERMISSIONS ###
GET {{baseUrl}}/api/admin/permissions
Authorization: Bearer {{adminAccess_token}}

### LIST ROLES ###
GET {{baseUrl}}/api/admin/roles/3
Authorization: Bearer {{adminAccess_token}}


### GET STATUSES ###
GET {{baseUrl}}/api/status
Authorization: Bearer {{adminAccess_token}}

### CREATE STATUS ###
POST {{baseUrl}}/api/admin/status
Authorization: Bearer {{adminAccess_token}}
Content-Type: application/json

{
    "name": "In Review",
    "description": "The ticket is being reviewed"
}   

### USERS ###
GET {{baseUrl}}/api/admin/users
Authorization: Bearer {{adminAccess_token}}


### GET USER 3 ###
GET {{baseUrl}}/api/admin/users/3
Authorization: Bearer {{adminAccess_token}}


### LIST Status ###
GET {{baseUrl}}/api/status
Authorization: Bearer {{adminAccess_token}}


### CREATE USER ROLE ###
POST {{baseUrl}}/api/admin/roles
Authorization: Bearer {{adminAccess_token}}
Content-Type: application/json

{
    "name": "SUPPORT",
    "description": "support role",
    "permissionIds": [4,5,6,31,32,41,42]
}


### CREATE USER ###
POST {{baseUrl}}/api/admin/users
Authorization: Bearer {{adminAccess_token}}
Content-Type: application/json

{
    "name": "Max Payne",
    "email": "max.payne@example.com",
    "password": "password1234",
    "roleIds": [3]
}

### GET 1 USER ###
GET {{baseUrl}}/api/admin/users/3
Authorization: Bearer {{adminAccess_token}}


### LIST USERS ###
GET {{baseUrl}}/api/admin/users/3
Authorization: Bearer {{adminAccess_token}}


###GET PERMISSIONS ###
GET {{baseUrl}}/api/admin/permissions
Authorization: Bearer {{adminAccess_token}}


###GET ROLES ###
GET {{baseUrl}}/api/admin/roles/2
Authorization: Bearer {{adminAccess_token}}



### ADD STATUS MANAGE TO ADMIN ###
### ADD PERMISSIONS TO ROLE ###
PATCH {{baseUrl}}/api/admin/roles/3/permissions
Authorization: Bearer {{adminAccess_token}}
Content-Type: application/json

[22]

### CREATE PRIORITY ###
POST {{baseUrl}}/api/admin/priorities
Authorization: Bearer {{adminAccess_token}}
Content-Type: application/json

{
    "name": "Low",
    "description": "Low priority"
}


### GET PRIORITIES ###
GET {{baseUrl}}/api/priorities
Authorization: Bearer {{adminAccess_token}}




###PATCH TICKET PRIORITY ###
PATCH {{baseUrl}}/api/admin/tickets/1
Authorization: Bearer {{adminAccess_token}}
Content-Type: application/json

{
    "priorityId": 2
}   


### GET TICKETS ###
GET {{baseUrl}}/api/tickets
Authorization: Bearer {{adminAccess_token}}


### DELETE PERMISSIONS FROM ROLE ###
DELETE {{baseUrl}}/api/admin/roles/2/permissions
Authorization: Bearer {{adminAccess_token}}
Content-Type: application/json

[4]