@baseUrl = http://localhost:8100

### LOGIN ADMIN USER ###
# @name admin
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
    "email": "admin@example.com",
    "password": "admin123"
}

@adminAccess_token = {{admin.response.body.data.access_token}}
@adminRefresh_token = {{admin.response.body.data.refresh_token}}


### CREATE USER ###
POST {{baseUrl}}/api/admin/users
Authorization: Bearer {{adminAccess_token}}
Content-Type: application/json

{
    "name": "Max Payne",
    "email": "max.payne@example.com",
    "password": "password1234",
    "roleIds": [2]
}


### GET CREATED USER ###
GET {{baseUrl}}/api/admin/users/3
Authorization: Bearer {{adminAccess_token}}


### GET ALL USERS ###
GET {{baseUrl}}/api/admin/users
Authorization: Bearer {{adminAccess_token}}