@baseUrl = http://localhost:8100

### LOGIN USER ###
# @name user
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
    "email": "gordon.freeman@example.com",
    "password": "password1234"
}

@Access_token = {{user.response.body.data.access_token}}
@Refresh_token = {{user.response.body.data.refresh_token}}
@userId = {{user.response.body.data.user.id}}


### GET PRIORITIES ###
GET {{baseUrl}}/api/priorities
Authorization: Bearer {{Access_token}}

### CREATE TICKET ### 
POST {{baseUrl}}/api/tickets
Content-Type: application/json
Authorization: Bearer {{Access_token}}

{
  "title": "Password reset email missing",
  "body": "I requested a password reset but never received the email. I checked spam and waited 15 minutes.",
  "priorityId": 2
}

### LIST TICKETS ###
GET {{baseUrl}}/api/tickets/1
Authorization: Bearer {{Access_token}}


### POST TICKET MESSAGE ###
POST {{baseUrl}}/api/tickets/1/messages
Content-Type: application/json
Authorization: Bearer {{Access_token}}

"I am still waiting for the password reset email. Please assist."
