@baseUrl = http://localhost:8100

### LOGIN USER ###
# @name user
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
    "email": "gordon.freeman@example.com",
    "password": "password1234"
}

@Access_token = {{user.response.body.data.access_token}}
@Refresh_token = {{user.response.body.data.refresh_token}}
@userId = {{user.response.body.data.user.id}}


### GET PRIORITIES ###
GET {{baseUrl}}/api/priorities
Authorization: Bearer {{Access_token}}

### CREATE TICKET ### 
POST {{baseUrl}}/api/tickets
Content-Type: application/json
Authorization: Bearer {{Access_token}}

{
  "title": "Ticket 1",
  "body": "Ticke 1 body content",
  "priorityId": 1
}

### CREATE TICKET ### 
POST {{baseUrl}}/api/tickets
Content-Type: application/json
Authorization: Bearer {{Access_token}}

{
  "title": "Ticket 2",
  "body": "Ticke 2 body content",
  "priorityId": 2
}

### CREATE TICKET ### 
POST {{baseUrl}}/api/tickets
Content-Type: application/json
Authorization: Bearer {{Access_token}}

{
  "title": "Ticket 3",
  "body": "Ticke 3 body content",
  "priorityId": 3
}

### CREATE TICKET ### 
POST {{baseUrl}}/api/tickets
Content-Type: application/json
Authorization: Bearer {{Access_token}}

{
  "title": "Ticket 4",
  "body": "Ticke 4 body content",
  "priorityId": 4
}

### LIST TICKETS ###
GET {{baseUrl}}/api/tickets
Authorization: Bearer {{Access_token}}

### GET 1 TICKETS ###
GET {{baseUrl}}/api/tickets/1
Authorization: Bearer {{Access_token}}


### POST TICKET MESSAGE ###
POST {{baseUrl}}/api/tickets/1/messages
Content-Type: application/json
Authorization: Bearer {{Access_token}}

{
    "message": "Do Something"
}