@baseUrl = http://localhost:8100

### LOGIN USER ###
# @name user
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
    "email": "gordon.freeman@example.com",
    "password": "password1234"
}

@Access_token = {{user.response.body.data.access_token}}
@Refresh_token = {{user.response.body.data.refresh_token}}


### GET PRIORITIES ###
GET {{baseUrl}}/api/priorities
Authorization: Bearer {{Access_token}}

### CREATE TICKET ### 
POST {{baseUrl}}/api/tickets
Content-Type: application/json
Authorization: Bearer {{Access_token}}

{
  "title": "Password reset email missing",
  "body": "I requested a password reset but never received the email. I checked spam and waited 15 minutes.",
  "priorityId": 2
}

### LIST TICKETS ###
GET {{baseUrl}}/api/tickets
Authorization: Bearer {{Access_token}}

### GET STATUSES ###
GET {{baseUrl}}/api/status
Authorization: Bearer {{Access_token}}


### GET USERS ###
GET {{baseUrl}}/api/users
Authorization: Bearer {{Access_token}}


### UPDATE / PATCH STATUS OF TICKET 1 ###
PATCH {{baseUrl}}/api/tickets/1/status
Authorization: Bearer {{Access_token}}
Content-Type: application/json

{
    "status_id": 1
}

