@baseUrl = http://localhost:8100

### LOGIN USER ###
# @name user
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
    "email": "max.payne@example.com",
    "password": "password1234"
}

@Access_token = {{user.response.body.data.access_token}}
@Refresh_token = {{user.response.body.data.refresh_token}}


### GET PRIORITIES ###
GET {{baseUrl}}/api/priorities
Authorization: Bearer {{Access_token}}

### CREATE TICKET 1 ### 
POST {{baseUrl}}/api/tickets
Content-Type: application/json
Authorization: Bearer {{Access_token}}

{
  "title": "User Max Payne cannot reset password",
  "body": "Max Payne is unable to reset his password as he is not receiving the reset email. Please investigate.",
  "priorityId": 2
}


### CREATE TICKET 2 ### 
POST {{baseUrl}}/api/tickets
Content-Type: application/json
Authorization: Bearer {{Access_token}}

{
  "title": "User Max Payne creating connection issues",
    "body": "Max Payne create issue",
    "priorityId": 3
}

### LIST TICKETS ###
GET {{baseUrl}}/api/tickets
Authorization: Bearer {{Access_token}}


### UPDATE TICKET ###
PUT {{baseUrl}}/api/tickets/5
Content-Type: application/json
Authorization: Bearer {{Access_token}}

{
  "title": "Updated Max Payne connection",
    "body": "Max Payne create Update",
    "priorityId": 3
}