@baseUrl = http://localhost:8100

### LOGIN USER ###
# @name user
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
    "email": "john@example.com",
    "password": "password1234"
}

@Access_token = {{user.response.body.data.access_token}}
@Refresh_token = {{user.response.body.data.refresh_token}}


### GET CURRENT USER ###
GET {{baseUrl}}/api/user
Authorization: Bearer {{Access_token}}

### GET PRIORITIES ###
GET {{baseUrl}}/api/priorities
Authorization: Bearer {{Access_token}}

### CREATE TICKET 1 ### 
POST {{baseUrl}}/api/tickets
Content-Type: application/json
Authorization: Bearer {{Access_token}}

{
  "title": "John Doe ID 4 creating issue",
  "body": "John Doe ID 4 create issue 1",
  "priorityId": 1
}


### CREATE TICKET 2 ### 
POST {{baseUrl}}/api/tickets
Content-Type: application/json
Authorization: Bearer {{Access_token}}

{
  "title": "John Doe creating issue 2",
    "body": "John Doe create issue 2",
    "priorityId": 3
}

### LIST TICKETS ###
GET {{baseUrl}}/api/tickets
Authorization: Bearer {{Access_token}}


### UPDATE TICKET ###
PUT {{baseUrl}}/api/tickets/6
Content-Type: application/json
Authorization: Bearer {{Access_token}}

{
  "title": "Max Payne Issue 1 - updated 1",
    "body": "Max Payne create issue 1 - updated 1",
    "priorityId": 4
}


### GET TICKETS ###
GET {{baseUrl}}/api/tickets
Authorization: Bearer {{Access_token}}